# This file sets default project configuration for the User Guides website generator
# See default Jekyll configuration at https://jekyllrb.com/docs/configuration/default/

title: Adobe Commerce 2.3 User Guide (Archived)

description: Merchant-focused documentation for both Adobe Commerce and Magento Open Source
logo: Commerce User Guide
baseurl: /user-guide/v2.3

destination: _site/user-guide/v2.3

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
theme: devdocs
source: src
plugins_dir: ./_plugins

version: 2.3

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: default
      lang: en
      github_link: false
      feedback_link: false

  -
    scope:
      path: catalog
    values:
      group: catalog
  -
    scope:
      path: cms
    values:
      group: content
  -
    scope:
      path: customers
    values:
      group: customers
  -
    scope:
      path: design
    values:
      group: content
  -
    scope:
      path: getting-started
    values:
      group: getting-started
  -
    scope:
      path: quick-tour
    values:
      group: getting-started
  -
    scope:
      path: marketing
    values:
      group: marketing
  -
    scope:
      path: product-recommendations
    values:
      group: marketing
  -
    scope:
      path: operations
    values:
      group: operations
  -
    scope:
      path: sales-channels
    values:
      group: marketing
  -
    scope:
      path: stores
    values:
      group: operations
  -
    scope:
      path: system
    values:
      group: operations
  -
    scope:
      path: tax
    values:
      group: operations
  -
    scope:
      path: reports
    values:
      group: operations
  -
    scope:
      path: mcom
    values:
      group: operations
  -
    scope:
      path: sales
    values:
      group: sales
  -
    scope:
      path: shipping
    values:
      group: sales
  -
    scope:
      path: payment
    values:
      group: sales
  -
    scope:
      path: configuration
    values:
      group: config-ref
  -
    scope:
      path: magento
    values:
      group: getting-started

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

livereload: true
check_links: true
